Update to version 1.1.1. New features include: * PDF, DocBook/XML, XHTML and Macromedia Flash (SWF) export * Accessibility * Support for Complex Text Layout (CTL) * User installation automated

diff --git a/misc/openoffice/files/soffice b/misc/openoffice/files/soffice
--- a/misc/openoffice/files/soffice
+++ b/misc/openoffice/files/soffice
@@ -1,9 +1,9 @@
 #!/bin/sh
 #
-#	$NetBSD: soffice,v 1.2 2003/05/19 02:58:19 simonb Exp $
+#	$NetBSD: soffice,v 1.5 2004/01/25 16:57:57 mrauch Exp $
 #
-SOINST=@@PREFIX@@/OpenOffice.org641
-[ "$SOFFICE" = "" ] && SOFFICE=$HOME/OpenOffice.org641
+SOINST=@@PREFIX@@/OpenOffice.org1.1.1
+[ "$SOFFICE" = "" ] && SOFFICE=$HOME/OpenOffice.org1.1.1
 
 if [ ! -d "$SOFFICE" ]; then
 	echo ""
@@ -18,12 +18,24 @@ if [ ! -d "$SOFFICE" ]; then
 	echo "-----------------------------------------------------------------"
 	echo ""
 
-# add an eventually existing java directory to $PATH to allow OO to 
-# automatically find it
-	export PATH=$PATH:@@PREFIX@@/java/bin
-
 	cd $SOINST
-	./setup
+	BASENAME=`basename $0`
+	TMPFILE=`mktemp -q /tmp/$BASENAME.XXXXXX`
+	if [ $? -ne 0 ]; then
+		echo "$0: Can't create temp file, exiting..."
+		exit 1
+	fi
+	cat << EOF >> ${TMPFILE} 
+[ENVIRONMENT]
+INSTALLATIONMODE=INSTALL_WORKSTATION
+INSTALLATIONTYPE=WORKSTATION
+DESTINATIONPATH=$SOFFICE
+OUTERPATH=
+LOGFILE=
+
+EOF
+	./setup -nogui -r:${TMPFILE}
+	rm -f ${TMPFILE}
 
 	echo ""
 	echo "Done.  Starting OpenOffice ..."
@@ -33,5 +45,9 @@ fi
 # We've got a large number of shared libraries and other single files which 
 # have to be open for normal operation
 ulimit -n `ulimit -n -H`
+if [ -z $PTHREAD_DIAGASSERT ]; then
+PTHREAD_DIAGASSERT=AEL
+export PTHREAD_DIAGASSERT
+fi
 
 exec ${SOFFICE}/soffice "$@"
