Fixed the infinite recursion as suggested in PR 41446. Thanks for the patch.

diff --git a/bootstrap/bootstrap b/bootstrap/bootstrap
--- a/bootstrap/bootstrap
+++ b/bootstrap/bootstrap
@@ -282,10 +282,15 @@ mkdir_p()
 
 mkdir_p_early()
 {
-	[ -d "$1" ] && return 0
-	mkdir -p "$1" && return 0
-	[ -d "$1" ] && return 0
-	die "aborted."
+	[ -d "$1" ] && return 0	
+	mkdir -p "$1" 2> /dev/null && return 0
+	parent=`dirname "$1"`
+	mkdir_p_early "$parent"
+	if [ ! -d "$1" ] && mkdir "$1"; then
+		echo_msg "mkdir $1 exited with status $?"
+		die "aborted."
+	fi
+	return 0
 }
 
 copy_src()
