Revert the change in 1.77, which does not work correctly.
However, this does not help people who are doing bulk builds
in sandboxes via read-only nullfs mounts.

A correct, long-term solution to this needs to be found.

diff --git a/mk/bulk/build b/mk/bulk/build
--- a/mk/bulk/build
+++ b/mk/bulk/build
@@ -215,20 +215,16 @@ show_config_vars
 #
 # Check that the package tools are up to date.
 #
-if [ -f /sandbox -a -x /sandbox ]; then
-	echo "Building in a sandbox - using existing pkgtools"
-else
-	( cd "${pkglint_dir}" \
-	  && ${BMAKE} fetch >/dev/null 2>&1
-	) || {
-		echo "Updating pkgtools"
-		( cd "${pkgsrc_dir}/pkgtools/pkg_install" \
-		  && ${BMAKE} clean \
-		  && ${BMAKE} install \
-		  && ${BMAKE} clean
-		) || die "Could not update the package tools."
-	}
-fi
+( cd "${pkglint_dir}" \
+  && ${BMAKE} fetch >/dev/null 2>&1
+) || {
+	echo "Updating pkgtools"
+	( cd "${pkgsrc_dir}/pkgtools/pkg_install" \
+	  && ${BMAKE} clean \
+	  && ${BMAKE} install \
+	  && ${BMAKE} clean
+	) || die "Could not update the package tools."
+}
 
 #
 # Run the pre-build script if necessary.
