Update abcde to 2.1.4nb5: 	Strip out \r from the end of the CDDB data to make editing easier

diff --git a/audio/abcde/patches/patch-ac b/audio/abcde/patches/patch-ac
--- a/audio/abcde/patches/patch-ac
+++ b/audio/abcde/patches/patch-ac
@@ -1,8 +1,8 @@
-$NetBSD: patch-ac,v 1.13 2003/07/12 15:25:55 wiz Exp $
+$NetBSD$
 
---- abcde.orig	Sun May 18 23:01:13 2003
+--- abcde.orig	Sun May 18 20:01:13 2003
 +++ abcde
-@@ -337,7 +337,7 @@
+@@ -337,7 +337,7 @@ do_batch_encode ()
  			do
  				TRACKFILES="$TRACKFILES track$UTRACKNUM.wav"
  			done
@@ -11,7 +11,20 @@ $NetBSD: patch-ac,v 1.13 2003/07/12 15:25:55 wiz Exp $
  			RETURN=$?
  			if [ "$RETURN" != "0" ]; then
  				echo "batch-encode: $ENCODER returned code $RETURN" >> errors
-@@ -1233,8 +1233,8 @@ if [ -z "$WAVOUTPUTDIR" ]; then
+@@ -928,7 +928,12 @@ do_cddbedit ()
+ 		echo "abcde: internal error: cddb-choice not recorded." >&2
+ 		exit 1
+ 	fi
++
++	# Strip out ^M
+ 	CDDBDATA="$ABCDETEMPDIR/cddbread.$(checkstatus cddb-choice)"
++	CDDBDATATMP="$ABCDETEMPDIR/cddbread.tmp"
++	tr -d '\r' < $CDDBDATA > $CDDBDATATMP
++	mv $CDDBDATATMP $CDDBDATA
+ 
+ 	if [ "$INTERACTIVE" = "y" ]; then
+ 		echo -n "Edit selected CDDB data? [y/n] (n): " >&2
+@@ -1233,8 +1238,8 @@ if [ -z "$WAVOUTPUTDIR" ]; then
  fi
  
  # Load system defaults
@@ -22,7 +35,7 @@ $NetBSD: patch-ac,v 1.13 2003/07/12 15:25:55 wiz Exp $
  fi
  # Load user preference defaults
  if [ -r $HOME/.abcde.conf ]; then
-@@ -1260,8 +1260,8 @@ else
+@@ -1260,8 +1265,8 @@ else
  	elif [ -e /dev/acd0c ]; then
  		CDROM=/dev/acd0c
  	else
@@ -33,7 +46,7 @@ $NetBSD: patch-ac,v 1.13 2003/07/12 15:25:55 wiz Exp $
  	fi
  fi
  
-@@ -1308,7 +1308,7 @@ done
+@@ -1308,7 +1313,7 @@ done
  case "$CDROMREADERSYNTAX" in
  	cdparanoia|debug)
  		CDROMREADER="$CDPARANOIA"
@@ -42,7 +55,7 @@ $NetBSD: patch-ac,v 1.13 2003/07/12 15:25:55 wiz Exp $
  		;;
  	cdda2wav)
  		CDROMREADER="$CDDA2WAV"
-@@ -1427,7 +1427,8 @@
+@@ -1427,7 +1432,8 @@ for X in $CDROMREADER $CDDISCID ${NEEDTA
  do
  	# Cut off the command-line options we just added in
  	X=$(echo $X | cut -d' ' -f2)
