Fix FLAC detection, and add dependency on flac package. Bump PKGREVISION to 1.

diff --git a/audio/easytag/patches/patch-aa b/audio/easytag/patches/patch-aa
--- a/audio/easytag/patches/patch-aa
+++ b/audio/easytag/patches/patch-aa
@@ -2,6 +2,15 @@ $NetBSD$
 
 --- configure.orig	Tue Dec 31 14:24:37 2002
 +++ configure
+@@ -8150,7 +8150,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_l
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; }; then
+-  . conftest.flac; echo "${LIBFLAC_MAJOR}.${LIBFLAC_MINOR}.${LIBFLAC_PATCH}"
++  . ./conftest.flac; echo "${LIBFLAC_MAJOR}.${LIBFLAC_MINOR}.${LIBFLAC_PATCH}"
+ else
+   echo "$as_me: program exited with status $ac_status" >&5
+ echo "$as_me: failed program was:" >&5
 @@ -8312,8 +8312,7 @@ int
  main ()
  {
