Update mail/courier-imap to courier-imap-4.0.1.  Changes from version 3.0.5 include:
    * Implemented IMAP and POP3 proxy aggregator.  With a proxy
      aggregator, the mail accounts are split between multiple,
      independent servers, with an IMAP/POP3 server running on each
      individual server.  A separate, proxy server sits in front and
      accepts ordinary IMAP and POP3 connections.  It reads the login
      ID, determines which server the account is located on, connects
      to the server, and logs in.  Then, for the lifetime on the login
      session the front-end server takes itself out of the loop, and
      forwards all session traffic between the IMAP/POP3 client, and
      the back-end server.

    * Use courier-authlib for user authentication.

    * IPv6 support.

    * Minor bug fixes.

Please note when updating that the locations of the userdb files has
changed to be within the courier-authlib config directory, e.g.
/usr/pkg/etc/authlib/userdb*.

diff --git a/mail/courier-imap/patches/patch-ad b/mail/courier-imap/patches/patch-ad
--- a/mail/courier-imap/patches/patch-ad
+++ b/mail/courier-imap/patches/patch-ad
@@ -1,8 +1,17 @@
 $NetBSD$
 
---- configure.orig	Thu Nov 27 15:51:08 2003
+--- configure.orig	2005-01-04 19:57:18.000000000 -0500
 +++ configure
-@@ -3607,9 +3607,6 @@ else
+@@ -19568,7 +19568,7 @@ echo "$as_me: error: courierauthconfig n
+ fi
+ $COURIERAUTHCONFIG --configfiles >conftest || exit 1
+ sed 's/^/auth/' <conftest >conftest2
+-. conftest2
++. ./conftest2
+ if test ! -x $authsbindir/courierlogger$EXEEXT
+ then
+ 	{ { echo "$as_me:$LINENO: error: authlib configuration error - $authsbindir/courierlogger$EXEEXT not found" >&5
+@@ -20376,9 +20376,6 @@ else
    ac_configure_args="$ac_configure_args --with-authchangepwdir=/var/tmp/dev/null"
  fi;
  
